### PR TITLE
Return a payment declined error on the frontend

### LINKED ISSUE #68: Handle instrument declined errors
Right now the extension throws an exception on instrument declined from PayPal, ideally we should just display an error to the customer prompting them to try again with a different payment method.

### PR DESCRIPTION
**Pull request by seand7565**
Previously, declined payments would cause an exception - this redirects the
user back to the payment page with an error that explains why.

Fixes #68

### CODE REVIEW

File: app/models/solidus_paypal_commerce_platform/gateway.rb [hunk 1]
```diff
@@ -23,15 +23,19 @@ def purchase(money, source, options)
       request = OrdersCaptureRequest.new(source.paypal_order_id)
       request.request_body(amount: { currency_code: options[:currency], value: Money.new(money).dollars })
       response = @client.execute_with_response(request)
-      capture_id = response.params["result"].purchase_units[0].payments.captures[0].id
-      source.update(capture_id: capture_id) if response.success?
+      if response.success?
+        capture_id = response.params["result"].purchase_units[0].payments.captures[0].id
+        source.update(capture_id: capture_id) if response.success?
```
Comment (elia) [inline app/models/solidus_paypal_commerce_platform/gateway.rb:28]: The tail check for `if response.success?` has been left there during the refactoring ✂️

Comment (seand7565) [reply app/models/solidus_paypal_commerce_platform/gateway.rb:28]: Whoops! 😬
